# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' test for y = x^2 in real mode
#' 
#' @param x double
#' @export
test_real <- function(x) {
    .Call(`_autodiffr_test_real`, x)
}

#' test for y = x^2 in real mode
#' 
#' @param x double
#' @export
test_dual <- function(x) {
    .Call(`_autodiffr_test_dual`, x)
}

#' derivative of 1 + x + x*x + 1/x + log(x) in forward mode
#' 
#' @export
test_forward_derivative <- function() {
    .Call(`_autodiffr_test_forward_derivative`)
}

#' gradient of (x * x.exp()).sum() in forward mode
#' 
#' @export
test_forward_gradient <- function() {
    .Call(`_autodiffr_test_forward_gradient`)
}

#' partial derivatives of 1 + x + y + z + x*y + y*z + x*z + x*y*z + exp(x/y + y/z) in forward mode
#' 
#' @examples
#' test_forward_derivative_multi()
#' @export
test_forward_derivative_multi <- function() {
    .Call(`_autodiffr_test_forward_derivative_multi`)
}

#' derivative of 1 + x + x*x + 1/x + log(x) in reserse mode
#' 
#' @export
test_reverse_derivative <- function() {
    .Call(`_autodiffr_test_reverse_derivative`)
}

#' gradient of (x * x.exp()).sum() in reverse mode
#' 
#' @export
test_reverse_gradient <- function() {
    .Call(`_autodiffr_test_reverse_gradient`)
}

#' partial derivatives of 1 + x + y + z + x*y + y*z + x*z + x*y*z + exp(x/y + y/z) in reverse mode
#'
#' @export
test_reverse_derivative_multi <- function() {
    .Call(`_autodiffr_test_reverse_derivative_multi`)
}

